# Generated by Django 5.2.1 on 2025-05-29 01:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(max_length=100)),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2026)])),
                ('is_available', models.BooleanField()),
                ('genra', models.CharField(choices=[('ACT', 'Action'), ('MYS', 'Mystery'), ('ADV', 'Adventure')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'movie_table',
                'ordering': ['-release_year'],
            },
        ),
    ]
