# Generated by Django 5.2.1 on 2025-05-30 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists_movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'actor',
                'verbose_name_plural': 'actors',
                'db_table': 'actor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'co_director',
                'verbose_name_plural': 'co_directors',
                'db_table': 'co_director',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'director',
                'verbose_name_plural': 'directors',
                'db_table': 'director_table',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='movies',
            name='actors',
            field=models.ManyToManyField(related_name='movie_actor', to='lists_movie.actor'),
        ),
        migrations.AddField(
            model_name='movies',
            name='codir',
            field=models.ManyToManyField(related_name='CoDirector', to='lists_movie.codirector'),
        ),
        migrations.AddField(
            model_name='movies',
            name='direct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_dir', to='lists_movie.director'),
        ),
    ]
