# Generated by Django 5.2.1 on 2025-05-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists_movie', '0002_actor_codirector_director_movies_actors_movies_codir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='email',
            field=models.EmailField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='codirector',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='codirector',
            name='email',
            field=models.EmailField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='codirector',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='director',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='email',
            field=models.EmailField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='director',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='codirector',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
